// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

[Table("Invoice")]
public partial class Invoice
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string StudentId { get; set; }

    [Required]
    [StringLength(50)]
    public string UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime NgayThu { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TongTienThu { get; set; }

    [Required]
    [StringLength(50)]
    public string HocKy { get; set; }

    public string GhiChu { get; set; }

    [ForeignKey("HocKy")]
    [InverseProperty("Invoices")]
    public virtual TutitionConfig HocKyNavigation { get; set; }

    [InverseProperty("Invoice")]
    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    [ForeignKey("StudentId")]
    [InverseProperty("Invoices")]
    public virtual Student Student { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Invoices")]
    public virtual User User { get; set; }
}