// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

[Table("InvoiceDetail")]
public partial class InvoiceDetail
{
    [Key]
    public int Id { get; set; }

    public int InvoiceId { get; set; }

    public int RegistrationId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal SoTienThanhToan { get; set; }

    [ForeignKey("InvoiceId")]
    [InverseProperty("InvoiceDetails")]
    public virtual Invoice Invoice { get; set; }

    [ForeignKey("RegistrationId")]
    [InverseProperty("InvoiceDetails")]
    public virtual StudentRegistration Registration { get; set; }
}