// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

public partial class QuanLiHocPhiContext : DbContext
{
    public QuanLiHocPhiContext()
    : base(new DbContextOptionsBuilder<QuanLiHocPhiContext>()
        .UseSqlServer("Server=localhost,1433;Database=QuanLiHocPhi;User Id=sa;Password=1413Kiet;TrustServerCertificate=True;")
        .Options)
    {
    }

    public QuanLiHocPhiContext(DbContextOptions<QuanLiHocPhiContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentRegistration> StudentRegistrations { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<TutitionConfig> TutitionConfigs { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=localhost,1433;Initial Catalog=QuanLiHocPhi;Persist Security Info=True;User ID=sa;Password=1413Kiet;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Invoice__3214EC077FF63E7D");

            entity.Property(e => e.NgayThu).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.HocKyNavigation).WithMany(p => p.Invoices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Invoice__HocKy__47DBAE45");

            entity.HasOne(d => d.Student).WithMany(p => p.Invoices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Invoice__Student__44FF419A");

            entity.HasOne(d => d.User).WithMany(p => p.Invoices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Invoice__UserId__45F365D3");
        });

        modelBuilder.Entity<InvoiceDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__InvoiceD__3214EC077F3AAEAE");

            entity.HasOne(d => d.Invoice).WithMany(p => p.InvoiceDetails).HasConstraintName("FK__InvoiceDe__Invoi__4AB81AF0");

            entity.HasOne(d => d.Registration).WithMany(p => p.InvoiceDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__InvoiceDe__Regis__4BAC3F29");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Student__3214EC070A717F0B");
        });

        modelBuilder.Entity<StudentRegistration>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__StudentR__3214EC078B24E70C");

            entity.HasOne(d => d.HocKyNavigation).WithMany(p => p.StudentRegistrations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StudentRe__HocKy__412EB0B6");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentRegistrations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StudentRe__Stude__3F466844");

            entity.HasOne(d => d.Subject).WithMany(p => p.StudentRegistrations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StudentRe__Subje__403A8C7D");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Subject__3214EC0729A6F555");
        });

        modelBuilder.Entity<TutitionConfig>(entity =>
        {
            entity.HasKey(e => e.HocKy).HasName("PK__Tutition__2BB032E4EA9F1DBB");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3214EC0780291E43");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}