// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

[Table("Student")]
public partial class Student
{
    [Key]
    [StringLength(20)]
    public string Id { get; set; }

    [Required]
    [StringLength(100)]
    public string HoDem { get; set; }

    [Required]
    [StringLength(50)]
    public string Ten { get; set; }

    [Required]
    [StringLength(150)]
    public string DisplayName { get; set; }

    public DateOnly? NgaySinh { get; set; }

    [StringLength(10)]
    public string GioiTinh { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    [StringLength(100)]
    public string Email { get; set; }

    [StringLength(50)]
    public string Lop { get; set; }

    [StringLength(100)]
    public string Nganh { get; set; }

    [StringLength(50)]
    public string TrangThai { get; set; }

    [InverseProperty("Student")]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    [InverseProperty("Student")]
    public virtual ICollection<StudentRegistration> StudentRegistrations { get; set; } = new List<StudentRegistration>();
}