// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

[Table("StudentRegistration")]
public partial class StudentRegistration
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(20)]
    public string StudentId { get; set; }

    [Required]
    [StringLength(20)]
    public string SubjectId { get; set; }

    [Required]
    [StringLength(50)]
    public string HocKy { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal DonGiaTaiThoiDiemDangKi { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TongTienHoc { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal SoTienDaDong { get; set; }

    [Required]
    [StringLength(50)]
    public string TrangThai { get; set; }

    [ForeignKey("HocKy")]
    [InverseProperty("StudentRegistrations")]
    public virtual TutitionConfig HocKyNavigation { get; set; }

    [InverseProperty("Registration")]
    public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; } = new List<InvoiceDetail>();

    [ForeignKey("StudentId")]
    [InverseProperty("StudentRegistrations")]
    public virtual Student Student { get; set; }

    [ForeignKey("SubjectId")]
    [InverseProperty("StudentRegistrations")]
    public virtual Subject Subject { get; set; }
}