// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

[Table("Subject")]
public partial class Subject
{
    [Key]
    [StringLength(20)]
    public string Id { get; set; }

    [Required]
    [StringLength(100)]
    public string DisplayName { get; set; }

    public int SoTinChi { get; set; }

    [StringLength(100)]
    public string BoMon { get; set; }

    [InverseProperty("Subject")]
    public virtual ICollection<StudentRegistration> StudentRegistrations { get; set; } = new List<StudentRegistration>();
}