// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

[Table("TutitionConfig")]
public partial class TutitionConfig
{
    [Key]
    [StringLength(50)]
    public string HocKy { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? DonGiaMotTinChi { get; set; }

    public string GhiChu { get; set; }

    [InverseProperty("HocKyNavigation")]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    [InverseProperty("HocKyNavigation")]
    public virtual ICollection<StudentRegistration> StudentRegistrations { get; set; } = new List<StudentRegistration>();
}