// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_QLHocPhi.Models;

[Table("User")]
public partial class User
{
    [Key]
    [StringLength(50)]
    public string Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [Required]
    [StringLength(100)]
    public string DisplayName { get; set; }

    [Required]
    [StringLength(50)]
    public string Role { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}